### ISSUE TITLE
Spot Request failed: bad-parameters

### ISSUE THREAD

**Issue by ijdfgh** [dan-v/copperheados-stack#1]
After fresh install with no modifications, EC2 reports failed Spot Requests.

> State: failed: Invalid value '' for keyPairNames. It should not be blank

Parameter "SSH_KEY_NAME = ''" in Lambda script is empty.

Thank you for this fantastic project.

**Comment by dan-v** [comment]
Thanks for testing this out. Haven't had anyone run it besides me before. I'll work on a fix soon. For now you could just manually change it in Lambda function or specify --ssh-key on CLI. Let me know if you hit any other issues.

**Comment by ijdfgh** [comment]
I edited the lambda script. Instance is now up and running. Will report back in the evening.

**Comment by ijdfgh** [comment]
The instance seems to be stuck. https://pastebin.com/NBbMceBf

It's been in this state for at least 40 minutes. Terminating instance and trying again now.

EDIT: opened a new issue.

**Comment by dan-v** [comment]
Fixed in latest version: https://github.com/dan-v/copperheados-stack/releases/tag/v0.0.6
