### ISSUE TITLE
Walleye build is missing vendor files

### ISSUE THREAD

**Issue by ijdfgh** [dan-v/copperheados-stack#3]
### Prerequisites

* [x] Are you running the latest version?

### Description

Walleye factory image only contains
>android-info.txt
>boot.img
>dtbo.img
>system.img
>vbmeta.img

After flashing, the phone fails to boot.

Stock Google image contains many more files. I suspect Muskie vendor files, which are required for Walleye (although it's not in the official build instructions, are missing.

### Steps to Reproduce

Start a build for walleye target.
Flash resulting factory image.

**Expected behavior:** Phone boots.

**Actual behavior:** Phone does not boot.

### Version

0.0.6

### Platform

linux

### Full Command Used for Setup

./copperheados-stack --region eu-west-2 --name copperheados-NAME --device walleye --ssh-key ssh_NAME

### Log output

I'll PM you the entire log (it's over 40MB), but here is a relevant snippet. Maybe I was wrong in guessing that Muskie files are not being incorporated.

>$ cat 1526097383 | grep muskie
>From https://github.com/copperheados/device_google_muskie
>Fetching project device_google_muskie
>including device/google/muskie/vendorsetup.sh
>[134/1001] including ./device/google/muskie/self-extractors/Android.mk ...
>[135/1001] including ./device/google/muskie/voice_processing/Android.mk ...
>  DTC     arch/arm64/boot/dts/htc/overlay-muskie-xa_xb_xc.dtbo
>  DTC     arch/arm64/boot/dts/htc/overlay-muskie-xd_xe.dtbo
>  DTC     arch/arm64/boot/dts/htc/overlay-muskie-xa_xb_xc.dtbo
>  DTC     arch/arm64/boot/dts/htc/overlay-muskie-xd_xe.dtbo
>[ 57% 57206/99635] AAPT2 compile out/target/product/walleye/obj/APPS./SystemUI_intermediates/flat-res/device/google/muskie/walleye/overlay/frameworks/base/packages/SystemUI/res/values_config.arsc.flat <- device/google/muskie/walleye/overlay/frameworks/base/packages/SystemUI/res/values/config.xml
>[ 73% 73611/99635] target thumb C: libqcomvoiceprocessingdescriptors_32 <= device/google/muskie/voice_processing/voice_processing_descriptors.c
>[ 74% 74250/99635] target  C: libqcomvoiceprocessingdescriptors <= device/google/muskie/voice_processing/voice_processing_descriptors.c
>[134/1001] including ./device/google/muskie/self-extractors/Android.mk ...
>[135/1001] including ./device/google/muskie/voice_processing/Android.mk ...

**Comment by ijdfgh** [comment]
I just learned that GitHub does not have a PM function. Here are download links:

(Last modified May 12, 2018 5:56:25 AM GMT+0200)
https://nofile.io/f/stTaAH8x0qN/1526097383

(Last modified May 12, 2018 5:56:28 AM GMT+0200)
https://nofile.io/f/a8wsPpUBJU4/1526097386

**Comment by dan-v** [comment]
Dang! Sorry your phone is offline. I've only run this with marlin so far and others are best guess based on documentation.

Yeah, I'm guessing it may be the vendor file issue, it's just not super clear in the documentation as it only mentions doing it for original pixel (https://copperhead.co/android/docs/building#extracting-vendor-files-for-nexus-and-pixel-devices). Let me get you a build that copies over vendor files for pixel 2 - and let's give it another shot.

**Comment by ijdfgh** [comment]
Thanks for the quick response! When I built the image myself, I executed the following after execute-all.sh:

>mkdir -p vendor/google_devices
>rm -rf vendor/google_devices/walleye
>rm -rf vendor/google_devices/muskie
>mv vendor/android-prepare-vendor/walleye/$BUILD_TAG/vendor/google_devices/muskie vendor/google_devices

>mv vendor/android-prepare-vendor/walleye/BUILD_TAG/vendor/google_devices/walleye vendor/google_devices

For illustration purposes, this is an image of the missing files: https://i.imgur.com/gBC9Go1.png
On the left is Google's factory image for comparison.

I hope this helps. You are awesome :)

**Comment by dan-v** [comment]
Alright here is new version with change: https://github.com/dan-v/copperheados-stack/releases/tag/v0.0.7
Change: https://github.com/dan-v/copperheados-stack/commit/789b0ddc725f3616ecaa3f0c4f69489464cbb3d3

This is my best guess fix. I'm trying to think of the best way to deploy again. You could try to keep what's there and just update stack, this time around should be quicker with no Chromium build.
* Run the same command to update your stack with latest code
* Delete factory-latest.tar.xz from S3 release bucket so you get a new one uploaded
* Edit your Lambda function and set FORCE_RUN to True as you already have a build  matching latest date (although it's bad) and execute the function.  (make sure to change this immediately back to False or you will keep building every 24 hours).

I'm heading to bed, but let me know how it turns out!

**Comment by ijdfgh** [comment]
Done!

I found that te EC2 instance from the previous build was still running by the way. If it happens again with this build I'll do some investigating as to why this happens.

**Comment by ijdfgh** [comment]
Works like a charm. Thanks!

**Comment by dan-v** [comment]
Awesome! 👍
