### ISSUE TITLE
Instance does not Terminate automatically

### ISSUE THREAD

**Issue by ijdfgh** [dan-v/copperheados-stack#4]
### Prerequisites

* [x] Are you running the latest version?

### Description

The instance fails to Terminate upon the build's completion.

### Steps to Reproduce

N/A

**Expected behavior:** After completing the build, the instance shuts down automatically.

**Actual behavior:** The instance is still up, hours after completing build.

### Version
0.0.7

### Platform
Linux

### Full Command Used for Setup

./copperheados-stack --region us-west-2 --name copperheados-dan --device walleye --ssh-key ssh-key

### Log output

The following is output straight after last upload to S3:

>/home/ubuntu/chos.sh: line 419: /usr/bin/aws: Argument list too long
>Cloud-init v. 17.1 running 'modules:final' at Sat, 12 May 2018 20:25:36 +0000. Up 14.57 seconds.
>2018-05-13 04:52:18,631 - util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/runcmd [1]
>2018-05-13 04:52:18,642 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
>2018-05-13 04:52:18,646 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
>Cloud-init v. 17.1 finished at Sun, 13 May 2018 04:52:18 +0000. Datasource DataSourceEc2Local.  Up 30415.96 seconds

**Comment by dan-v** [comment]
Hey! Thanks for the bug report. I'll take a look at this when I have some time. Not super worried about it as I have configured the spot instance to run for a maximum of 12 hours (this should probably be reduced also). You could manually modify this in your lambda function (valid_until) for now if you're worried about it.

**Comment by dan-v** [comment]
Looks like a quick fix, so I pushed new version. Thanks for the detailed report, made it easy to track down.

**Comment by ijdfgh** [comment]
Thanks for the quick fix, you are fantastic! I'll test when the next CHOS release comes around.
