### ISSUE TITLE
OTA/Update option is not present in Settings>System

### ISSUE THREAD

**Issue by ijdfgh** [dan-v/copperheados-stack#5]
### Prerequisites

* [x] Are you running the latest version?

### Description

"System updates" option is not present in Settings>System.

I am unable to verify wether OTA functions at all as of now. Don't know how often it is supposed to check on itself.

### Steps to Reproduce

Go to Settings app, open System category.

**Expected behavior:**
"System updates" is present, allowing me to force check for update.

**Actual behavior:**
"System updates" is not present.

### Version

0.0.9

### Platform
Linux

### Full Command Used for Setup

Still the same.

### Log output

I'm trying not to disclose my bucket name, as to comply with Copperhead's 'no distribution of binaries' clause. Please let me know if you need logs.

**Comment by dan-v** [comment]
I think I may know what the issue is here. I should have time this week to take a look.

**Comment by ijdfgh** [comment]
Thank you so much.

**Comment by dan-v** [comment]
Alright give this version a shot: https://github.com/dan-v/copperheados-stack/releases/tag/v0.0.10. It's just a guess on the fix since I don't have the device.

**Comment by ijdfgh** [comment]
Flashed today. Unfortunately the fix did not work.

When I enter "updates" in the "Search settings" field inside the Settings app, it suggests "System updates". When I press it, I am taken to the System menu, where it lists 

>Language & input
>Gestures
>Date & time
>Backup
>Reset options
>About phone

System updates is still missing.

Please let me know if there is anything I can provide you with that would help in investigating this issue. I will dive into your changes in version 0.0.9 to 0.0.10 to see if I can figure this out.

**Comment by ijdfgh** [comment]
Are the following lines of build_script.go correct?

>225 +  if [ "$DEVICE" == 'walleye' ]; then
>226 +    pushd "$CHOS_DIR"/device/google/muskie

I mean, shouldn't there also be:

>  pushd "$CHOS_DIR"/device/google/walleye

I'm just guessing, really.

**Comment by dan-v** [comment]
My original guess on why it didn't work is because the CopperheadOS updater app (https://github.com/CopperheadOS/platform_packages_apps_Updater/) is likely not being included in the build for Pixel 2. For Pixel build, the marlin folder gets the updater app included in a .mk file so that it is included in build. My attempt to fix it was just adding the updater app to one of the .mk files used in pixel 2 builds. Can you see if the Updater app is present in the resulting build files?

**Comment by ijdfgh** [comment]
What .mk file it being included in for Marlin?

I found this in the log:

>[572/1001] including ./packages/apps/Updater/Android.mk ...

>[ 75% 76200/101160] Copy: out/target/product/walleye/system/priv-app/Updater/oat/arm64/Updater.odex
>[ 75% 76201/101160] Copy: out/target/product/walleye/system/priv-app/Updater/oat/arm64/Updater.vdex

>[ 75% 76203/101160] target Package: Updater (out/target/product/walleye/obj/APPS/Updater_intermediates/package.apk)
>[ 75% 76204/101160] Install: out/target/product/walleye/system/priv-app/Updater/Updater.apk

I also looked through the app list on my phone and can confirm that the app is indeed not installed.

**Comment by ijdfgh** [comment]
May have stumbled upon something here. "PRODUCT_PACKAGES += \" is in "device_google_muskie/blob/oreo-m2-release/aosp_walleye.mk", not "device_google_muskie/blob/oreo-m2-release/device-common.mk".

Edit: Running a build now to try this.

**Comment by dan-v** [comment]
Hmm that log line above seems to show it is installing the app. Did you look through the system apps (apps->see all apps->right hand dropdown->show system apps)? It's listed as CopperheadOS Updater. Anyways, let me know how it goes.

**Comment by ijdfgh** [comment]
Yeah, I looked through the system app. 

I am unable to adb sideload the ota zips (apparently due to an incompatible USB-A to USB-C cable). I did not realise that the factory.tar.gz is not being overwritten. Long story short: the flash I did yesterday (after updating to 0.0.10) was actually old.

Have a build running now with 

>  if [ "$DEVICE" == 'walleye' ]; then
>    pushd "$CHOS_DIR"/device/google/muskie
>    sed -i.original "\$aPRODUCT_PACKAGES += Updater" aosp_walleye.mk
>  fi
> 
>  if [ "$DEVICE" == 'walleye' ]; then
>    pushd "$CHOS_DIR"/device/google/wahoo
>    sed -i.original "\$aPRODUCT_PACKAGES += Updater" device.mk
>  fi
>  
>  if [ "$DEVICE" == 'walleye' ]; then
>    pushd "$CHOS_DIR"/device/google/muskie
>    sed -i.original "\$aPRODUCT_PACKAGES += Updater" device-common.mk
>  fi

Don't know if this is a smart idea, but thought it couldn't hurt. Let's see how it turns out. If it does not work I'll revert to 0.0.10 and try again.

**Comment by ijdfgh** [comment]
Success! The Updater app is now present.

Went back into the logs and was able to conclude that the fix you pushed for 0.0.10 did in fact work. 

No further modification is needed, disregard my previous comment.
